version: '3.8'
services:
  frontend:
    build: .
    ports:
      - "3000:3000"
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/pet-shop
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"